"""
Build the bundled exercise demo pictures (Phase 2) from the Everkinetic drawings.

Source: Everkinetic open data, https://github.com/everkinetic/data (by Greg Priday),
licensed CC BY-SA 4.0. Each exercise has two drawings — "relaxation" (start) and
"tension" (end) — on one shared canvas, so they loop cleanly.

Changes made here (the licence requires saying so; the results are shared under the same
licence, CC BY-SA 4.0): the black-on-white line art is recoloured to light lines on a
transparent background for the app's dark theme, rendered at 560 px on the long side,
and saved as lossless WebP; a 128 px square thumbnail is cut from the end frame.

  python scripts/build-exercise-media.py <catalog.json>

Reads every entry with an "ek" id from the catalogue JSON, downloads the two SVGs once
(cached in .media-cache/, git-ignored), renders them with scripts/render-svg.mjs, and writes:
  assets/exercises/<key>__0.webp, <key>__1.webp, <key>__t.webp
  src/tracker/catalog/media.ts   (static require() map; regenerated, do not edit)
"""
import io
import json
import os
import subprocess
import sys
import urllib.request

from PIL import Image, ImageChops, ImageOps

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CACHE = os.path.join(ROOT, '.media-cache', 'everkinetic')
OUT = os.path.join(ROOT, 'assets', 'exercises')
TS = os.path.join(ROOT, 'src', 'tracker', 'catalog', 'media.ts')
RAW = 'https://raw.githubusercontent.com/everkinetic/data/master/dist/svg/{id}-{frame}.svg'
INK = (230, 232, 238)
FRAME_PX = 560
THUMB_PX = 128


def fetch(ek: str, frame: str) -> str:
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, f'{ek}-{frame}.svg')
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        with urllib.request.urlopen(RAW.format(id=ek, frame=frame), timeout=60) as r:
            data = r.read()
        with open(path, 'wb') as f:
            f.write(data)
    return path


def ink(png_path: str) -> Image.Image:
    """Black lines on white → light lines on transparent (white fills stay see-through)."""
    im = Image.open(png_path).convert('RGBA')
    dark = ImageOps.invert(im.convert('L'))
    alpha = ImageChops.multiply(dark, im.getchannel('A'))
    out = Image.new('RGBA', im.size, INK + (255,))
    out.putalpha(alpha)
    return out


def thumb(frame: Image.Image) -> Image.Image:
    box = frame.getbbox() or (0, 0, frame.width, frame.height)
    art = frame.crop(box)
    art.thumbnail((THUMB_PX - 12, THUMB_PX - 12), Image.LANCZOS)
    canvas = Image.new('RGBA', (THUMB_PX, THUMB_PX), (0, 0, 0, 0))
    canvas.alpha_composite(art, ((THUMB_PX - art.width) // 2, (THUMB_PX - art.height) // 2))
    return canvas


def main() -> None:
    catalog = json.load(open(sys.argv[1], encoding='utf-8'))
    entries = [e for e in catalog if e.get('ek')]
    os.makedirs(OUT, exist_ok=True)
    tmp = os.path.join(CACHE, 'png')
    os.makedirs(tmp, exist_ok=True)

    # Render every SVG in one node call per 40 files (fast, no per-file start-up).
    jobs = []
    for e in entries:
        for i, frame in enumerate(('relaxation', 'tension')):
            jobs.append((fetch(e['ek'], frame), os.path.join(tmp, f"{e['key']}__{i}.png")))
    for start in range(0, len(jobs), 40):
        args = ['node', os.path.join(ROOT, 'scripts', 'render-svg.mjs'), str(FRAME_PX)]
        for src, dst in jobs[start:start + 40]:
            args += [src, dst]
        subprocess.run(args, check=True)

    wanted = set()
    total = 0
    for e in entries:
        frames = [ink(os.path.join(tmp, f"{e['key']}__{i}.png")) for i in (0, 1)]
        for i, f in enumerate(frames):
            name = f"{e['key']}__{i}.webp"
            f.save(os.path.join(OUT, name), 'WEBP', lossless=True, method=6)
            wanted.add(name)
        t = thumb(frames[1])
        name = f"{e['key']}__t.webp"
        t.save(os.path.join(OUT, name), 'WEBP', lossless=True, method=6)
        wanted.add(name)
    # Drop pictures of entries that no longer have a drawing.
    for f in os.listdir(OUT):
        if f.endswith('.webp') and f not in wanted:
            os.remove(os.path.join(OUT, f))
    for f in wanted:
        total += os.path.getsize(os.path.join(OUT, f))

    lines = [
        '/**',
        ' * GENERATED by scripts/build-exercise-media.py — do not edit by hand.',
        ' *',
        ' * Demo pictures: Everkinetic open data (https://github.com/everkinetic/data, by Greg Priday),',
        ' * CC BY-SA 4.0. Recoloured to light lines for the dark theme and converted to WebP; these',
        ' * changed pictures are shared under the same licence.',
        ' */',
        "import type { ImageSourcePropType } from 'react-native';",
        '',
        'export interface ExerciseMedia {',
        '  /** Small square picture for lists. */',
        '  thumb: ImageSourcePropType;',
        '  /** Start and end positions; the demo loops between them. */',
        '  frames: readonly [ImageSourcePropType, ImageSourcePropType];',
        '}',
        '',
        '/** Credit shown wherever a library drawing appears (CC BY-SA 4.0 attribution). */',
        "export const MEDIA_CREDIT = 'Drawing: Everkinetic, CC BY-SA 4.0, recoloured';",
        "export const MEDIA_LICENCE_URL = 'https://creativecommons.org/licenses/by-sa/4.0/';",
        '',
        '/* eslint-disable @typescript-eslint/no-require-imports */',
        'export const EXERCISE_MEDIA: Readonly<Record<string, ExerciseMedia>> = {',
    ]
    for e in sorted(entries, key=lambda x: x['key']):
        k = e['key']
        lines.append(f"  {k}: {{")
        lines.append(f"    thumb: require('../../../assets/exercises/{k}__t.webp'),")
        lines.append(f"    frames: [require('../../../assets/exercises/{k}__0.webp'), require('../../../assets/exercises/{k}__1.webp')],")
        lines.append('  },')
    lines += [
        '};',
        '',
        'export function mediaFor(key: string | null | undefined): ExerciseMedia | null {',
        '  if (!key) return null;',
        '  return EXERCISE_MEDIA[key] ?? null;',
        '}',
        '',
    ]
    with open(TS, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print(f'{len(entries)} exercises, {len(wanted)} files, {total / 1e6:.2f} MB')


if __name__ == '__main__':
    main()
