/**
 * GENERATED by scripts/build-exercise-media.py — do not edit by hand.
 *
 * Demo pictures: Everkinetic open data (https://github.com/everkinetic/data, by Greg Priday),
 * CC BY-SA 4.0. Recoloured to light lines for the dark theme and converted to WebP; these
 * changed pictures are shared under the same licence.
 */
import type { ImageSourcePropType } from 'react-native';

export interface ExerciseMedia {
  /** Small square picture for lists. */
  thumb: ImageSourcePropType;
  /** Start and end positions; the demo loops between them. */
  frames: readonly [ImageSourcePropType, ImageSourcePropType];
}

/** Credit shown wherever a library drawing appears (CC BY-SA 4.0 attribution). */
export const MEDIA_CREDIT = 'Drawing: Everkinetic, CC BY-SA 4.0, recoloured';
export const MEDIA_LICENCE_URL = 'https://creativecommons.org/licenses/by-sa/4.0/';

/* eslint-disable @typescript-eslint/no-require-imports */
export const EXERCISE_MEDIA: Readonly<Record<string, ExerciseMedia>> = {
  alternating_dumbbell_curl: {
    thumb: require('../../../assets/exercises/alternating_dumbbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/alternating_dumbbell_curl__0.webp'), require('../../../assets/exercises/alternating_dumbbell_curl__1.webp')],
  },
  alternating_hammer_curl: {
    thumb: require('../../../assets/exercises/alternating_hammer_curl__t.webp'),
    frames: [require('../../../assets/exercises/alternating_hammer_curl__0.webp'), require('../../../assets/exercises/alternating_hammer_curl__1.webp')],
  },
  back_extension: {
    thumb: require('../../../assets/exercises/back_extension__t.webp'),
    frames: [require('../../../assets/exercises/back_extension__0.webp'), require('../../../assets/exercises/back_extension__1.webp')],
  },
  barbell_back_squat: {
    thumb: require('../../../assets/exercises/barbell_back_squat__t.webp'),
    frames: [require('../../../assets/exercises/barbell_back_squat__0.webp'), require('../../../assets/exercises/barbell_back_squat__1.webp')],
  },
  barbell_bench_press: {
    thumb: require('../../../assets/exercises/barbell_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/barbell_bench_press__0.webp'), require('../../../assets/exercises/barbell_bench_press__1.webp')],
  },
  barbell_bulgarian_split_squat: {
    thumb: require('../../../assets/exercises/barbell_bulgarian_split_squat__t.webp'),
    frames: [require('../../../assets/exercises/barbell_bulgarian_split_squat__0.webp'), require('../../../assets/exercises/barbell_bulgarian_split_squat__1.webp')],
  },
  barbell_calf_raise: {
    thumb: require('../../../assets/exercises/barbell_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/barbell_calf_raise__0.webp'), require('../../../assets/exercises/barbell_calf_raise__1.webp')],
  },
  barbell_curl: {
    thumb: require('../../../assets/exercises/barbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/barbell_curl__0.webp'), require('../../../assets/exercises/barbell_curl__1.webp')],
  },
  barbell_drag_curl: {
    thumb: require('../../../assets/exercises/barbell_drag_curl__t.webp'),
    frames: [require('../../../assets/exercises/barbell_drag_curl__0.webp'), require('../../../assets/exercises/barbell_drag_curl__1.webp')],
  },
  barbell_lunge: {
    thumb: require('../../../assets/exercises/barbell_lunge__t.webp'),
    frames: [require('../../../assets/exercises/barbell_lunge__0.webp'), require('../../../assets/exercises/barbell_lunge__1.webp')],
  },
  barbell_preacher_curl: {
    thumb: require('../../../assets/exercises/barbell_preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/barbell_preacher_curl__0.webp'), require('../../../assets/exercises/barbell_preacher_curl__1.webp')],
  },
  barbell_pullover: {
    thumb: require('../../../assets/exercises/barbell_pullover__t.webp'),
    frames: [require('../../../assets/exercises/barbell_pullover__0.webp'), require('../../../assets/exercises/barbell_pullover__1.webp')],
  },
  barbell_reverse_lunge: {
    thumb: require('../../../assets/exercises/barbell_reverse_lunge__t.webp'),
    frames: [require('../../../assets/exercises/barbell_reverse_lunge__0.webp'), require('../../../assets/exercises/barbell_reverse_lunge__1.webp')],
  },
  barbell_rollout: {
    thumb: require('../../../assets/exercises/barbell_rollout__t.webp'),
    frames: [require('../../../assets/exercises/barbell_rollout__0.webp'), require('../../../assets/exercises/barbell_rollout__1.webp')],
  },
  barbell_row: {
    thumb: require('../../../assets/exercises/barbell_row__t.webp'),
    frames: [require('../../../assets/exercises/barbell_row__0.webp'), require('../../../assets/exercises/barbell_row__1.webp')],
  },
  barbell_shrug: {
    thumb: require('../../../assets/exercises/barbell_shrug__t.webp'),
    frames: [require('../../../assets/exercises/barbell_shrug__0.webp'), require('../../../assets/exercises/barbell_shrug__1.webp')],
  },
  barbell_skull_crusher: {
    thumb: require('../../../assets/exercises/barbell_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/barbell_skull_crusher__0.webp'), require('../../../assets/exercises/barbell_skull_crusher__1.webp')],
  },
  barbell_spider_curl: {
    thumb: require('../../../assets/exercises/barbell_spider_curl__t.webp'),
    frames: [require('../../../assets/exercises/barbell_spider_curl__0.webp'), require('../../../assets/exercises/barbell_spider_curl__1.webp')],
  },
  barbell_step_up: {
    thumb: require('../../../assets/exercises/barbell_step_up__t.webp'),
    frames: [require('../../../assets/exercises/barbell_step_up__0.webp'), require('../../../assets/exercises/barbell_step_up__1.webp')],
  },
  barbell_sumo_squat: {
    thumb: require('../../../assets/exercises/barbell_sumo_squat__t.webp'),
    frames: [require('../../../assets/exercises/barbell_sumo_squat__0.webp'), require('../../../assets/exercises/barbell_sumo_squat__1.webp')],
  },
  barbell_upright_row: {
    thumb: require('../../../assets/exercises/barbell_upright_row__t.webp'),
    frames: [require('../../../assets/exercises/barbell_upright_row__0.webp'), require('../../../assets/exercises/barbell_upright_row__1.webp')],
  },
  behind_the_head_skull_crusher: {
    thumb: require('../../../assets/exercises/behind_the_head_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/behind_the_head_skull_crusher__0.webp'), require('../../../assets/exercises/behind_the_head_skull_crusher__1.webp')],
  },
  bench_dip: {
    thumb: require('../../../assets/exercises/bench_dip__t.webp'),
    frames: [require('../../../assets/exercises/bench_dip__0.webp'), require('../../../assets/exercises/bench_dip__1.webp')],
  },
  bent_over_cable_rear_delt_raise: {
    thumb: require('../../../assets/exercises/bent_over_cable_rear_delt_raise__t.webp'),
    frames: [require('../../../assets/exercises/bent_over_cable_rear_delt_raise__0.webp'), require('../../../assets/exercises/bent_over_cable_rear_delt_raise__1.webp')],
  },
  bicycle_crunch: {
    thumb: require('../../../assets/exercises/bicycle_crunch__t.webp'),
    frames: [require('../../../assets/exercises/bicycle_crunch__0.webp'), require('../../../assets/exercises/bicycle_crunch__1.webp')],
  },
  box_squat: {
    thumb: require('../../../assets/exercises/box_squat__t.webp'),
    frames: [require('../../../assets/exercises/box_squat__0.webp'), require('../../../assets/exercises/box_squat__1.webp')],
  },
  cable_curl: {
    thumb: require('../../../assets/exercises/cable_curl__t.webp'),
    frames: [require('../../../assets/exercises/cable_curl__0.webp'), require('../../../assets/exercises/cable_curl__1.webp')],
  },
  cable_fly: {
    thumb: require('../../../assets/exercises/cable_fly__t.webp'),
    frames: [require('../../../assets/exercises/cable_fly__0.webp'), require('../../../assets/exercises/cable_fly__1.webp')],
  },
  cable_glute_kickback: {
    thumb: require('../../../assets/exercises/cable_glute_kickback__t.webp'),
    frames: [require('../../../assets/exercises/cable_glute_kickback__0.webp'), require('../../../assets/exercises/cable_glute_kickback__1.webp')],
  },
  cable_hip_adduction: {
    thumb: require('../../../assets/exercises/cable_hip_adduction__t.webp'),
    frames: [require('../../../assets/exercises/cable_hip_adduction__0.webp'), require('../../../assets/exercises/cable_hip_adduction__1.webp')],
  },
  cable_preacher_curl: {
    thumb: require('../../../assets/exercises/cable_preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/cable_preacher_curl__0.webp'), require('../../../assets/exercises/cable_preacher_curl__1.webp')],
  },
  cable_shrug: {
    thumb: require('../../../assets/exercises/cable_shrug__t.webp'),
    frames: [require('../../../assets/exercises/cable_shrug__0.webp'), require('../../../assets/exercises/cable_shrug__1.webp')],
  },
  cable_skull_crusher: {
    thumb: require('../../../assets/exercises/cable_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/cable_skull_crusher__0.webp'), require('../../../assets/exercises/cable_skull_crusher__1.webp')],
  },
  cable_upright_row: {
    thumb: require('../../../assets/exercises/cable_upright_row__t.webp'),
    frames: [require('../../../assets/exercises/cable_upright_row__0.webp'), require('../../../assets/exercises/cable_upright_row__1.webp')],
  },
  chest_dip: {
    thumb: require('../../../assets/exercises/chest_dip__t.webp'),
    frames: [require('../../../assets/exercises/chest_dip__0.webp'), require('../../../assets/exercises/chest_dip__1.webp')],
  },
  chest_supported_reverse_fly: {
    thumb: require('../../../assets/exercises/chest_supported_reverse_fly__t.webp'),
    frames: [require('../../../assets/exercises/chest_supported_reverse_fly__0.webp'), require('../../../assets/exercises/chest_supported_reverse_fly__1.webp')],
  },
  close_grip_barbell_curl: {
    thumb: require('../../../assets/exercises/close_grip_barbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/close_grip_barbell_curl__0.webp'), require('../../../assets/exercises/close_grip_barbell_curl__1.webp')],
  },
  close_grip_bench_press: {
    thumb: require('../../../assets/exercises/close_grip_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/close_grip_bench_press__0.webp'), require('../../../assets/exercises/close_grip_bench_press__1.webp')],
  },
  close_grip_ez_bar_curl: {
    thumb: require('../../../assets/exercises/close_grip_ez_bar_curl__t.webp'),
    frames: [require('../../../assets/exercises/close_grip_ez_bar_curl__0.webp'), require('../../../assets/exercises/close_grip_ez_bar_curl__1.webp')],
  },
  close_grip_lat_pulldown: {
    thumb: require('../../../assets/exercises/close_grip_lat_pulldown__t.webp'),
    frames: [require('../../../assets/exercises/close_grip_lat_pulldown__0.webp'), require('../../../assets/exercises/close_grip_lat_pulldown__1.webp')],
  },
  close_grip_push_up: {
    thumb: require('../../../assets/exercises/close_grip_push_up__t.webp'),
    frames: [require('../../../assets/exercises/close_grip_push_up__0.webp'), require('../../../assets/exercises/close_grip_push_up__1.webp')],
  },
  concentration_curl: {
    thumb: require('../../../assets/exercises/concentration_curl__t.webp'),
    frames: [require('../../../assets/exercises/concentration_curl__0.webp'), require('../../../assets/exercises/concentration_curl__1.webp')],
  },
  cross_body_crunch: {
    thumb: require('../../../assets/exercises/cross_body_crunch__t.webp'),
    frames: [require('../../../assets/exercises/cross_body_crunch__0.webp'), require('../../../assets/exercises/cross_body_crunch__1.webp')],
  },
  cross_body_hammer_curl: {
    thumb: require('../../../assets/exercises/cross_body_hammer_curl__t.webp'),
    frames: [require('../../../assets/exercises/cross_body_hammer_curl__0.webp'), require('../../../assets/exercises/cross_body_hammer_curl__1.webp')],
  },
  crunch: {
    thumb: require('../../../assets/exercises/crunch__t.webp'),
    frames: [require('../../../assets/exercises/crunch__0.webp'), require('../../../assets/exercises/crunch__1.webp')],
  },
  deadlift: {
    thumb: require('../../../assets/exercises/deadlift__t.webp'),
    frames: [require('../../../assets/exercises/deadlift__0.webp'), require('../../../assets/exercises/deadlift__1.webp')],
  },
  decline_barbell_bench_press: {
    thumb: require('../../../assets/exercises/decline_barbell_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/decline_barbell_bench_press__0.webp'), require('../../../assets/exercises/decline_barbell_bench_press__1.webp')],
  },
  decline_crunch: {
    thumb: require('../../../assets/exercises/decline_crunch__t.webp'),
    frames: [require('../../../assets/exercises/decline_crunch__0.webp'), require('../../../assets/exercises/decline_crunch__1.webp')],
  },
  decline_dumbbell_fly: {
    thumb: require('../../../assets/exercises/decline_dumbbell_fly__t.webp'),
    frames: [require('../../../assets/exercises/decline_dumbbell_fly__0.webp'), require('../../../assets/exercises/decline_dumbbell_fly__1.webp')],
  },
  decline_dumbbell_press: {
    thumb: require('../../../assets/exercises/decline_dumbbell_press__t.webp'),
    frames: [require('../../../assets/exercises/decline_dumbbell_press__0.webp'), require('../../../assets/exercises/decline_dumbbell_press__1.webp')],
  },
  decline_dumbbell_skull_crusher: {
    thumb: require('../../../assets/exercises/decline_dumbbell_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/decline_dumbbell_skull_crusher__0.webp'), require('../../../assets/exercises/decline_dumbbell_skull_crusher__1.webp')],
  },
  decline_ez_bar_skull_crusher: {
    thumb: require('../../../assets/exercises/decline_ez_bar_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/decline_ez_bar_skull_crusher__0.webp'), require('../../../assets/exercises/decline_ez_bar_skull_crusher__1.webp')],
  },
  decline_machine_chest_press: {
    thumb: require('../../../assets/exercises/decline_machine_chest_press__t.webp'),
    frames: [require('../../../assets/exercises/decline_machine_chest_press__0.webp'), require('../../../assets/exercises/decline_machine_chest_press__1.webp')],
  },
  decline_oblique_crunch: {
    thumb: require('../../../assets/exercises/decline_oblique_crunch__t.webp'),
    frames: [require('../../../assets/exercises/decline_oblique_crunch__0.webp'), require('../../../assets/exercises/decline_oblique_crunch__1.webp')],
  },
  decline_push_up: {
    thumb: require('../../../assets/exercises/decline_push_up__t.webp'),
    frames: [require('../../../assets/exercises/decline_push_up__0.webp'), require('../../../assets/exercises/decline_push_up__1.webp')],
  },
  donkey_calf_raise: {
    thumb: require('../../../assets/exercises/donkey_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/donkey_calf_raise__0.webp'), require('../../../assets/exercises/donkey_calf_raise__1.webp')],
  },
  dumbbell_bench_press: {
    thumb: require('../../../assets/exercises/dumbbell_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_bench_press__0.webp'), require('../../../assets/exercises/dumbbell_bench_press__1.webp')],
  },
  dumbbell_curl: {
    thumb: require('../../../assets/exercises/dumbbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_curl__0.webp'), require('../../../assets/exercises/dumbbell_curl__1.webp')],
  },
  dumbbell_deadlift: {
    thumb: require('../../../assets/exercises/dumbbell_deadlift__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_deadlift__0.webp'), require('../../../assets/exercises/dumbbell_deadlift__1.webp')],
  },
  dumbbell_fly: {
    thumb: require('../../../assets/exercises/dumbbell_fly__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_fly__0.webp'), require('../../../assets/exercises/dumbbell_fly__1.webp')],
  },
  dumbbell_front_raise: {
    thumb: require('../../../assets/exercises/dumbbell_front_raise__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_front_raise__0.webp'), require('../../../assets/exercises/dumbbell_front_raise__1.webp')],
  },
  dumbbell_lunge: {
    thumb: require('../../../assets/exercises/dumbbell_lunge__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_lunge__0.webp'), require('../../../assets/exercises/dumbbell_lunge__1.webp')],
  },
  dumbbell_preacher_curl: {
    thumb: require('../../../assets/exercises/dumbbell_preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_preacher_curl__0.webp'), require('../../../assets/exercises/dumbbell_preacher_curl__1.webp')],
  },
  dumbbell_pullover: {
    thumb: require('../../../assets/exercises/dumbbell_pullover__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_pullover__0.webp'), require('../../../assets/exercises/dumbbell_pullover__1.webp')],
  },
  dumbbell_reverse_curl: {
    thumb: require('../../../assets/exercises/dumbbell_reverse_curl__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_reverse_curl__0.webp'), require('../../../assets/exercises/dumbbell_reverse_curl__1.webp')],
  },
  dumbbell_reverse_lunge: {
    thumb: require('../../../assets/exercises/dumbbell_reverse_lunge__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_reverse_lunge__0.webp'), require('../../../assets/exercises/dumbbell_reverse_lunge__1.webp')],
  },
  dumbbell_shrug: {
    thumb: require('../../../assets/exercises/dumbbell_shrug__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_shrug__0.webp'), require('../../../assets/exercises/dumbbell_shrug__1.webp')],
  },
  dumbbell_side_bend: {
    thumb: require('../../../assets/exercises/dumbbell_side_bend__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_side_bend__0.webp'), require('../../../assets/exercises/dumbbell_side_bend__1.webp')],
  },
  dumbbell_skull_crusher: {
    thumb: require('../../../assets/exercises/dumbbell_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_skull_crusher__0.webp'), require('../../../assets/exercises/dumbbell_skull_crusher__1.webp')],
  },
  dumbbell_spider_curl: {
    thumb: require('../../../assets/exercises/dumbbell_spider_curl__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_spider_curl__0.webp'), require('../../../assets/exercises/dumbbell_spider_curl__1.webp')],
  },
  dumbbell_squat: {
    thumb: require('../../../assets/exercises/dumbbell_squat__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_squat__0.webp'), require('../../../assets/exercises/dumbbell_squat__1.webp')],
  },
  dumbbell_step_up: {
    thumb: require('../../../assets/exercises/dumbbell_step_up__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_step_up__0.webp'), require('../../../assets/exercises/dumbbell_step_up__1.webp')],
  },
  dumbbell_triceps_kickback: {
    thumb: require('../../../assets/exercises/dumbbell_triceps_kickback__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_triceps_kickback__0.webp'), require('../../../assets/exercises/dumbbell_triceps_kickback__1.webp')],
  },
  dumbbell_upright_row: {
    thumb: require('../../../assets/exercises/dumbbell_upright_row__t.webp'),
    frames: [require('../../../assets/exercises/dumbbell_upright_row__0.webp'), require('../../../assets/exercises/dumbbell_upright_row__1.webp')],
  },
  ez_bar_curl: {
    thumb: require('../../../assets/exercises/ez_bar_curl__t.webp'),
    frames: [require('../../../assets/exercises/ez_bar_curl__0.webp'), require('../../../assets/exercises/ez_bar_curl__1.webp')],
  },
  flat_bench_cable_fly: {
    thumb: require('../../../assets/exercises/flat_bench_cable_fly__t.webp'),
    frames: [require('../../../assets/exercises/flat_bench_cable_fly__0.webp'), require('../../../assets/exercises/flat_bench_cable_fly__1.webp')],
  },
  front_squat: {
    thumb: require('../../../assets/exercises/front_squat__t.webp'),
    frames: [require('../../../assets/exercises/front_squat__0.webp'), require('../../../assets/exercises/front_squat__1.webp')],
  },
  glute_bridge: {
    thumb: require('../../../assets/exercises/glute_bridge__t.webp'),
    frames: [require('../../../assets/exercises/glute_bridge__0.webp'), require('../../../assets/exercises/glute_bridge__1.webp')],
  },
  good_morning: {
    thumb: require('../../../assets/exercises/good_morning__t.webp'),
    frames: [require('../../../assets/exercises/good_morning__0.webp'), require('../../../assets/exercises/good_morning__1.webp')],
  },
  hack_squat: {
    thumb: require('../../../assets/exercises/hack_squat__t.webp'),
    frames: [require('../../../assets/exercises/hack_squat__0.webp'), require('../../../assets/exercises/hack_squat__1.webp')],
  },
  hammer_curl: {
    thumb: require('../../../assets/exercises/hammer_curl__t.webp'),
    frames: [require('../../../assets/exercises/hammer_curl__0.webp'), require('../../../assets/exercises/hammer_curl__1.webp')],
  },
  hip_abduction_machine: {
    thumb: require('../../../assets/exercises/hip_abduction_machine__t.webp'),
    frames: [require('../../../assets/exercises/hip_abduction_machine__0.webp'), require('../../../assets/exercises/hip_abduction_machine__1.webp')],
  },
  hip_adduction_machine: {
    thumb: require('../../../assets/exercises/hip_adduction_machine__t.webp'),
    frames: [require('../../../assets/exercises/hip_adduction_machine__0.webp'), require('../../../assets/exercises/hip_adduction_machine__1.webp')],
  },
  incline_barbell_press: {
    thumb: require('../../../assets/exercises/incline_barbell_press__t.webp'),
    frames: [require('../../../assets/exercises/incline_barbell_press__0.webp'), require('../../../assets/exercises/incline_barbell_press__1.webp')],
  },
  incline_barbell_skull_crusher: {
    thumb: require('../../../assets/exercises/incline_barbell_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/incline_barbell_skull_crusher__0.webp'), require('../../../assets/exercises/incline_barbell_skull_crusher__1.webp')],
  },
  incline_bench_preacher_curl: {
    thumb: require('../../../assets/exercises/incline_bench_preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/incline_bench_preacher_curl__0.webp'), require('../../../assets/exercises/incline_bench_preacher_curl__1.webp')],
  },
  incline_cable_fly: {
    thumb: require('../../../assets/exercises/incline_cable_fly__t.webp'),
    frames: [require('../../../assets/exercises/incline_cable_fly__0.webp'), require('../../../assets/exercises/incline_cable_fly__1.webp')],
  },
  incline_cable_triceps_extension: {
    thumb: require('../../../assets/exercises/incline_cable_triceps_extension__t.webp'),
    frames: [require('../../../assets/exercises/incline_cable_triceps_extension__0.webp'), require('../../../assets/exercises/incline_cable_triceps_extension__1.webp')],
  },
  incline_dumbbell_curl: {
    thumb: require('../../../assets/exercises/incline_dumbbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/incline_dumbbell_curl__0.webp'), require('../../../assets/exercises/incline_dumbbell_curl__1.webp')],
  },
  incline_dumbbell_fly: {
    thumb: require('../../../assets/exercises/incline_dumbbell_fly__t.webp'),
    frames: [require('../../../assets/exercises/incline_dumbbell_fly__0.webp'), require('../../../assets/exercises/incline_dumbbell_fly__1.webp')],
  },
  incline_dumbbell_press: {
    thumb: require('../../../assets/exercises/incline_dumbbell_press__t.webp'),
    frames: [require('../../../assets/exercises/incline_dumbbell_press__0.webp'), require('../../../assets/exercises/incline_dumbbell_press__1.webp')],
  },
  incline_dumbbell_skull_crusher: {
    thumb: require('../../../assets/exercises/incline_dumbbell_skull_crusher__t.webp'),
    frames: [require('../../../assets/exercises/incline_dumbbell_skull_crusher__0.webp'), require('../../../assets/exercises/incline_dumbbell_skull_crusher__1.webp')],
  },
  incline_neutral_grip_dumbbell_press: {
    thumb: require('../../../assets/exercises/incline_neutral_grip_dumbbell_press__t.webp'),
    frames: [require('../../../assets/exercises/incline_neutral_grip_dumbbell_press__0.webp'), require('../../../assets/exercises/incline_neutral_grip_dumbbell_press__1.webp')],
  },
  inverted_row: {
    thumb: require('../../../assets/exercises/inverted_row__t.webp'),
    frames: [require('../../../assets/exercises/inverted_row__0.webp'), require('../../../assets/exercises/inverted_row__1.webp')],
  },
  jm_press: {
    thumb: require('../../../assets/exercises/jm_press__t.webp'),
    frames: [require('../../../assets/exercises/jm_press__0.webp'), require('../../../assets/exercises/jm_press__1.webp')],
  },
  lateral_raise: {
    thumb: require('../../../assets/exercises/lateral_raise__t.webp'),
    frames: [require('../../../assets/exercises/lateral_raise__0.webp'), require('../../../assets/exercises/lateral_raise__1.webp')],
  },
  leg_extension: {
    thumb: require('../../../assets/exercises/leg_extension__t.webp'),
    frames: [require('../../../assets/exercises/leg_extension__0.webp'), require('../../../assets/exercises/leg_extension__1.webp')],
  },
  leg_press: {
    thumb: require('../../../assets/exercises/leg_press__t.webp'),
    frames: [require('../../../assets/exercises/leg_press__0.webp'), require('../../../assets/exercises/leg_press__1.webp')],
  },
  leg_press_calf_raise: {
    thumb: require('../../../assets/exercises/leg_press_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/leg_press_calf_raise__0.webp'), require('../../../assets/exercises/leg_press_calf_raise__1.webp')],
  },
  lying_cable_curl: {
    thumb: require('../../../assets/exercises/lying_cable_curl__t.webp'),
    frames: [require('../../../assets/exercises/lying_cable_curl__0.webp'), require('../../../assets/exercises/lying_cable_curl__1.webp')],
  },
  lying_leg_curl: {
    thumb: require('../../../assets/exercises/lying_leg_curl__t.webp'),
    frames: [require('../../../assets/exercises/lying_leg_curl__0.webp'), require('../../../assets/exercises/lying_leg_curl__1.webp')],
  },
  lying_leg_raise: {
    thumb: require('../../../assets/exercises/lying_leg_raise__t.webp'),
    frames: [require('../../../assets/exercises/lying_leg_raise__0.webp'), require('../../../assets/exercises/lying_leg_raise__1.webp')],
  },
  lying_rope_triceps_extension: {
    thumb: require('../../../assets/exercises/lying_rope_triceps_extension__t.webp'),
    frames: [require('../../../assets/exercises/lying_rope_triceps_extension__0.webp'), require('../../../assets/exercises/lying_rope_triceps_extension__1.webp')],
  },
  machine_bicep_curl: {
    thumb: require('../../../assets/exercises/machine_bicep_curl__t.webp'),
    frames: [require('../../../assets/exercises/machine_bicep_curl__0.webp'), require('../../../assets/exercises/machine_bicep_curl__1.webp')],
  },
  machine_chest_press: {
    thumb: require('../../../assets/exercises/machine_chest_press__t.webp'),
    frames: [require('../../../assets/exercises/machine_chest_press__0.webp'), require('../../../assets/exercises/machine_chest_press__1.webp')],
  },
  machine_triceps_extension: {
    thumb: require('../../../assets/exercises/machine_triceps_extension__t.webp'),
    frames: [require('../../../assets/exercises/machine_triceps_extension__0.webp'), require('../../../assets/exercises/machine_triceps_extension__1.webp')],
  },
  neutral_grip_pull_up: {
    thumb: require('../../../assets/exercises/neutral_grip_pull_up__t.webp'),
    frames: [require('../../../assets/exercises/neutral_grip_pull_up__0.webp'), require('../../../assets/exercises/neutral_grip_pull_up__1.webp')],
  },
  one_arm_dumbbell_row: {
    thumb: require('../../../assets/exercises/one_arm_dumbbell_row__t.webp'),
    frames: [require('../../../assets/exercises/one_arm_dumbbell_row__0.webp'), require('../../../assets/exercises/one_arm_dumbbell_row__1.webp')],
  },
  overhead_cable_curl: {
    thumb: require('../../../assets/exercises/overhead_cable_curl__t.webp'),
    frames: [require('../../../assets/exercises/overhead_cable_curl__0.webp'), require('../../../assets/exercises/overhead_cable_curl__1.webp')],
  },
  overhead_squat: {
    thumb: require('../../../assets/exercises/overhead_squat__t.webp'),
    frames: [require('../../../assets/exercises/overhead_squat__0.webp'), require('../../../assets/exercises/overhead_squat__1.webp')],
  },
  overhead_triceps_extension: {
    thumb: require('../../../assets/exercises/overhead_triceps_extension__t.webp'),
    frames: [require('../../../assets/exercises/overhead_triceps_extension__0.webp'), require('../../../assets/exercises/overhead_triceps_extension__1.webp')],
  },
  plate_reverse_curl: {
    thumb: require('../../../assets/exercises/plate_reverse_curl__t.webp'),
    frames: [require('../../../assets/exercises/plate_reverse_curl__0.webp'), require('../../../assets/exercises/plate_reverse_curl__1.webp')],
  },
  preacher_curl: {
    thumb: require('../../../assets/exercises/preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/preacher_curl__0.webp'), require('../../../assets/exercises/preacher_curl__1.webp')],
  },
  preacher_hammer_curl: {
    thumb: require('../../../assets/exercises/preacher_hammer_curl__t.webp'),
    frames: [require('../../../assets/exercises/preacher_hammer_curl__0.webp'), require('../../../assets/exercises/preacher_hammer_curl__1.webp')],
  },
  pull_up: {
    thumb: require('../../../assets/exercises/pull_up__t.webp'),
    frames: [require('../../../assets/exercises/pull_up__0.webp'), require('../../../assets/exercises/pull_up__1.webp')],
  },
  push_up: {
    thumb: require('../../../assets/exercises/push_up__t.webp'),
    frames: [require('../../../assets/exercises/push_up__0.webp'), require('../../../assets/exercises/push_up__1.webp')],
  },
  rear_delt_fly: {
    thumb: require('../../../assets/exercises/rear_delt_fly__t.webp'),
    frames: [require('../../../assets/exercises/rear_delt_fly__0.webp'), require('../../../assets/exercises/rear_delt_fly__1.webp')],
  },
  reverse_crunch: {
    thumb: require('../../../assets/exercises/reverse_crunch__t.webp'),
    frames: [require('../../../assets/exercises/reverse_crunch__0.webp'), require('../../../assets/exercises/reverse_crunch__1.webp')],
  },
  reverse_grip_barbell_row: {
    thumb: require('../../../assets/exercises/reverse_grip_barbell_row__t.webp'),
    frames: [require('../../../assets/exercises/reverse_grip_barbell_row__0.webp'), require('../../../assets/exercises/reverse_grip_barbell_row__1.webp')],
  },
  reverse_grip_bench_press: {
    thumb: require('../../../assets/exercises/reverse_grip_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/reverse_grip_bench_press__0.webp'), require('../../../assets/exercises/reverse_grip_bench_press__1.webp')],
  },
  reverse_grip_lat_pulldown: {
    thumb: require('../../../assets/exercises/reverse_grip_lat_pulldown__t.webp'),
    frames: [require('../../../assets/exercises/reverse_grip_lat_pulldown__0.webp'), require('../../../assets/exercises/reverse_grip_lat_pulldown__1.webp')],
  },
  reverse_grip_triceps_pushdown: {
    thumb: require('../../../assets/exercises/reverse_grip_triceps_pushdown__t.webp'),
    frames: [require('../../../assets/exercises/reverse_grip_triceps_pushdown__0.webp'), require('../../../assets/exercises/reverse_grip_triceps_pushdown__1.webp')],
  },
  romanian_deadlift: {
    thumb: require('../../../assets/exercises/romanian_deadlift__t.webp'),
    frames: [require('../../../assets/exercises/romanian_deadlift__0.webp'), require('../../../assets/exercises/romanian_deadlift__1.webp')],
  },
  rope_hammer_curl: {
    thumb: require('../../../assets/exercises/rope_hammer_curl__t.webp'),
    frames: [require('../../../assets/exercises/rope_hammer_curl__0.webp'), require('../../../assets/exercises/rope_hammer_curl__1.webp')],
  },
  rope_triceps_pushdown: {
    thumb: require('../../../assets/exercises/rope_triceps_pushdown__t.webp'),
    frames: [require('../../../assets/exercises/rope_triceps_pushdown__0.webp'), require('../../../assets/exercises/rope_triceps_pushdown__1.webp')],
  },
  seated_barbell_calf_raise: {
    thumb: require('../../../assets/exercises/seated_barbell_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/seated_barbell_calf_raise__0.webp'), require('../../../assets/exercises/seated_barbell_calf_raise__1.webp')],
  },
  seated_barbell_overhead_extension: {
    thumb: require('../../../assets/exercises/seated_barbell_overhead_extension__t.webp'),
    frames: [require('../../../assets/exercises/seated_barbell_overhead_extension__0.webp'), require('../../../assets/exercises/seated_barbell_overhead_extension__1.webp')],
  },
  seated_barbell_shoulder_press: {
    thumb: require('../../../assets/exercises/seated_barbell_shoulder_press__t.webp'),
    frames: [require('../../../assets/exercises/seated_barbell_shoulder_press__0.webp'), require('../../../assets/exercises/seated_barbell_shoulder_press__1.webp')],
  },
  seated_cable_rear_delt_fly: {
    thumb: require('../../../assets/exercises/seated_cable_rear_delt_fly__t.webp'),
    frames: [require('../../../assets/exercises/seated_cable_rear_delt_fly__0.webp'), require('../../../assets/exercises/seated_cable_rear_delt_fly__1.webp')],
  },
  seated_calf_raise: {
    thumb: require('../../../assets/exercises/seated_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/seated_calf_raise__0.webp'), require('../../../assets/exercises/seated_calf_raise__1.webp')],
  },
  seated_dip_machine: {
    thumb: require('../../../assets/exercises/seated_dip_machine__t.webp'),
    frames: [require('../../../assets/exercises/seated_dip_machine__0.webp'), require('../../../assets/exercises/seated_dip_machine__1.webp')],
  },
  seated_dumbbell_calf_raise: {
    thumb: require('../../../assets/exercises/seated_dumbbell_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/seated_dumbbell_calf_raise__0.webp'), require('../../../assets/exercises/seated_dumbbell_calf_raise__1.webp')],
  },
  seated_dumbbell_curl: {
    thumb: require('../../../assets/exercises/seated_dumbbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/seated_dumbbell_curl__0.webp'), require('../../../assets/exercises/seated_dumbbell_curl__1.webp')],
  },
  seated_leg_curl: {
    thumb: require('../../../assets/exercises/seated_leg_curl__t.webp'),
    frames: [require('../../../assets/exercises/seated_leg_curl__0.webp'), require('../../../assets/exercises/seated_leg_curl__1.webp')],
  },
  seated_overhead_dumbbell_extension: {
    thumb: require('../../../assets/exercises/seated_overhead_dumbbell_extension__t.webp'),
    frames: [require('../../../assets/exercises/seated_overhead_dumbbell_extension__0.webp'), require('../../../assets/exercises/seated_overhead_dumbbell_extension__1.webp')],
  },
  side_plank: {
    thumb: require('../../../assets/exercises/side_plank__t.webp'),
    frames: [require('../../../assets/exercises/side_plank__0.webp'), require('../../../assets/exercises/side_plank__1.webp')],
  },
  single_arm_cable_curl: {
    thumb: require('../../../assets/exercises/single_arm_cable_curl__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_cable_curl__0.webp'), require('../../../assets/exercises/single_arm_cable_curl__1.webp')],
  },
  single_arm_cable_front_raise: {
    thumb: require('../../../assets/exercises/single_arm_cable_front_raise__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_cable_front_raise__0.webp'), require('../../../assets/exercises/single_arm_cable_front_raise__1.webp')],
  },
  single_arm_dumbbell_bench_press: {
    thumb: require('../../../assets/exercises/single_arm_dumbbell_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_dumbbell_bench_press__0.webp'), require('../../../assets/exercises/single_arm_dumbbell_bench_press__1.webp')],
  },
  single_arm_dumbbell_preacher_curl: {
    thumb: require('../../../assets/exercises/single_arm_dumbbell_preacher_curl__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_dumbbell_preacher_curl__0.webp'), require('../../../assets/exercises/single_arm_dumbbell_preacher_curl__1.webp')],
  },
  single_arm_dumbbell_shoulder_press: {
    thumb: require('../../../assets/exercises/single_arm_dumbbell_shoulder_press__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_dumbbell_shoulder_press__0.webp'), require('../../../assets/exercises/single_arm_dumbbell_shoulder_press__1.webp')],
  },
  single_arm_dumbbell_upright_row: {
    thumb: require('../../../assets/exercises/single_arm_dumbbell_upright_row__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_dumbbell_upright_row__0.webp'), require('../../../assets/exercises/single_arm_dumbbell_upright_row__1.webp')],
  },
  single_arm_lying_dumbbell_extension: {
    thumb: require('../../../assets/exercises/single_arm_lying_dumbbell_extension__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_lying_dumbbell_extension__0.webp'), require('../../../assets/exercises/single_arm_lying_dumbbell_extension__1.webp')],
  },
  single_arm_overhead_cable_extension: {
    thumb: require('../../../assets/exercises/single_arm_overhead_cable_extension__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_overhead_cable_extension__0.webp'), require('../../../assets/exercises/single_arm_overhead_cable_extension__1.webp')],
  },
  single_arm_overhead_dumbbell_extension: {
    thumb: require('../../../assets/exercises/single_arm_overhead_dumbbell_extension__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_overhead_dumbbell_extension__0.webp'), require('../../../assets/exercises/single_arm_overhead_dumbbell_extension__1.webp')],
  },
  single_arm_reverse_grip_pushdown: {
    thumb: require('../../../assets/exercises/single_arm_reverse_grip_pushdown__t.webp'),
    frames: [require('../../../assets/exercises/single_arm_reverse_grip_pushdown__0.webp'), require('../../../assets/exercises/single_arm_reverse_grip_pushdown__1.webp')],
  },
  smith_machine_bench_press: {
    thumb: require('../../../assets/exercises/smith_machine_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_bench_press__0.webp'), require('../../../assets/exercises/smith_machine_bench_press__1.webp')],
  },
  smith_machine_deadlift: {
    thumb: require('../../../assets/exercises/smith_machine_deadlift__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_deadlift__0.webp'), require('../../../assets/exercises/smith_machine_deadlift__1.webp')],
  },
  smith_machine_good_morning: {
    thumb: require('../../../assets/exercises/smith_machine_good_morning__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_good_morning__0.webp'), require('../../../assets/exercises/smith_machine_good_morning__1.webp')],
  },
  smith_machine_incline_press: {
    thumb: require('../../../assets/exercises/smith_machine_incline_press__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_incline_press__0.webp'), require('../../../assets/exercises/smith_machine_incline_press__1.webp')],
  },
  smith_machine_row: {
    thumb: require('../../../assets/exercises/smith_machine_row__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_row__0.webp'), require('../../../assets/exercises/smith_machine_row__1.webp')],
  },
  smith_machine_squat: {
    thumb: require('../../../assets/exercises/smith_machine_squat__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_squat__0.webp'), require('../../../assets/exercises/smith_machine_squat__1.webp')],
  },
  smith_machine_upright_row: {
    thumb: require('../../../assets/exercises/smith_machine_upright_row__t.webp'),
    frames: [require('../../../assets/exercises/smith_machine_upright_row__0.webp'), require('../../../assets/exercises/smith_machine_upright_row__1.webp')],
  },
  stability_ball_back_extension: {
    thumb: require('../../../assets/exercises/stability_ball_back_extension__t.webp'),
    frames: [require('../../../assets/exercises/stability_ball_back_extension__0.webp'), require('../../../assets/exercises/stability_ball_back_extension__1.webp')],
  },
  stability_ball_crunch: {
    thumb: require('../../../assets/exercises/stability_ball_crunch__t.webp'),
    frames: [require('../../../assets/exercises/stability_ball_crunch__0.webp'), require('../../../assets/exercises/stability_ball_crunch__1.webp')],
  },
  stability_ball_knee_tuck: {
    thumb: require('../../../assets/exercises/stability_ball_knee_tuck__t.webp'),
    frames: [require('../../../assets/exercises/stability_ball_knee_tuck__0.webp'), require('../../../assets/exercises/stability_ball_knee_tuck__1.webp')],
  },
  standing_barbell_overhead_extension: {
    thumb: require('../../../assets/exercises/standing_barbell_overhead_extension__t.webp'),
    frames: [require('../../../assets/exercises/standing_barbell_overhead_extension__0.webp'), require('../../../assets/exercises/standing_barbell_overhead_extension__1.webp')],
  },
  standing_calf_raise: {
    thumb: require('../../../assets/exercises/standing_calf_raise__t.webp'),
    frames: [require('../../../assets/exercises/standing_calf_raise__0.webp'), require('../../../assets/exercises/standing_calf_raise__1.webp')],
  },
  standing_leg_curl: {
    thumb: require('../../../assets/exercises/standing_leg_curl__t.webp'),
    frames: [require('../../../assets/exercises/standing_leg_curl__0.webp'), require('../../../assets/exercises/standing_leg_curl__1.webp')],
  },
  stomach_vacuum: {
    thumb: require('../../../assets/exercises/stomach_vacuum__t.webp'),
    frames: [require('../../../assets/exercises/stomach_vacuum__0.webp'), require('../../../assets/exercises/stomach_vacuum__1.webp')],
  },
  straight_arm_pulldown: {
    thumb: require('../../../assets/exercises/straight_arm_pulldown__t.webp'),
    frames: [require('../../../assets/exercises/straight_arm_pulldown__0.webp'), require('../../../assets/exercises/straight_arm_pulldown__1.webp')],
  },
  straight_bar_cable_row: {
    thumb: require('../../../assets/exercises/straight_bar_cable_row__t.webp'),
    frames: [require('../../../assets/exercises/straight_bar_cable_row__0.webp'), require('../../../assets/exercises/straight_bar_cable_row__1.webp')],
  },
  sumo_squat: {
    thumb: require('../../../assets/exercises/sumo_squat__t.webp'),
    frames: [require('../../../assets/exercises/sumo_squat__0.webp'), require('../../../assets/exercises/sumo_squat__1.webp')],
  },
  superman: {
    thumb: require('../../../assets/exercises/superman__t.webp'),
    frames: [require('../../../assets/exercises/superman__0.webp'), require('../../../assets/exercises/superman__1.webp')],
  },
  t_bar_row: {
    thumb: require('../../../assets/exercises/t_bar_row__t.webp'),
    frames: [require('../../../assets/exercises/t_bar_row__0.webp'), require('../../../assets/exercises/t_bar_row__1.webp')],
  },
  tate_press: {
    thumb: require('../../../assets/exercises/tate_press__t.webp'),
    frames: [require('../../../assets/exercises/tate_press__0.webp'), require('../../../assets/exercises/tate_press__1.webp')],
  },
  triceps_dip: {
    thumb: require('../../../assets/exercises/triceps_dip__t.webp'),
    frames: [require('../../../assets/exercises/triceps_dip__0.webp'), require('../../../assets/exercises/triceps_dip__1.webp')],
  },
  triceps_pushdown: {
    thumb: require('../../../assets/exercises/triceps_pushdown__t.webp'),
    frames: [require('../../../assets/exercises/triceps_pushdown__0.webp'), require('../../../assets/exercises/triceps_pushdown__1.webp')],
  },
  two_arm_dumbbell_kickback: {
    thumb: require('../../../assets/exercises/two_arm_dumbbell_kickback__t.webp'),
    frames: [require('../../../assets/exercises/two_arm_dumbbell_kickback__0.webp'), require('../../../assets/exercises/two_arm_dumbbell_kickback__1.webp')],
  },
  v_bar_triceps_pushdown: {
    thumb: require('../../../assets/exercises/v_bar_triceps_pushdown__t.webp'),
    frames: [require('../../../assets/exercises/v_bar_triceps_pushdown__0.webp'), require('../../../assets/exercises/v_bar_triceps_pushdown__1.webp')],
  },
  walking_lunge: {
    thumb: require('../../../assets/exercises/walking_lunge__t.webp'),
    frames: [require('../../../assets/exercises/walking_lunge__0.webp'), require('../../../assets/exercises/walking_lunge__1.webp')],
  },
  weighted_sissy_squat: {
    thumb: require('../../../assets/exercises/weighted_sissy_squat__t.webp'),
    frames: [require('../../../assets/exercises/weighted_sissy_squat__0.webp'), require('../../../assets/exercises/weighted_sissy_squat__1.webp')],
  },
  wide_grip_barbell_curl: {
    thumb: require('../../../assets/exercises/wide_grip_barbell_curl__t.webp'),
    frames: [require('../../../assets/exercises/wide_grip_barbell_curl__0.webp'), require('../../../assets/exercises/wide_grip_barbell_curl__1.webp')],
  },
  wide_grip_bench_press: {
    thumb: require('../../../assets/exercises/wide_grip_bench_press__t.webp'),
    frames: [require('../../../assets/exercises/wide_grip_bench_press__0.webp'), require('../../../assets/exercises/wide_grip_bench_press__1.webp')],
  },
  zottman_curl: {
    thumb: require('../../../assets/exercises/zottman_curl__t.webp'),
    frames: [require('../../../assets/exercises/zottman_curl__0.webp'), require('../../../assets/exercises/zottman_curl__1.webp')],
  },
};

export function mediaFor(key: string | null | undefined): ExerciseMedia | null {
  if (!key) return null;
  return EXERCISE_MEDIA[key] ?? null;
}
